### ISSUE TITLE
xfile - find_file_in_zip tries to open a non-workbook xml file

### ISSUE THREAD

**Issue by itsmarco** [tableau/document-api-python#117] opened 2016-12-05 15:19 UTC
Hello,

I was parsing some packaged workbooks with and I encountered a problem. A .twbx I was trying to open had a bunch of .key files in it, which adhere to some xml structure. The function find_file_in_zip tries to pass this xml file on as a .twb, ultimately raising an tableaudocumentapi.xfile.TableauVersionNotSupportedException: 0.0 error. 

The workbook is actually a valid workbook, and ended up not getting parsed. Manually excluding .key files fixed the issue for me. 

Cheers,
Marco

**Comment by t8y8** [comment] 2016-12-05 18:16
@itsmarco would it be possible to attach a workbook that reproduces the issue?

I think I see where the problem is -- we return the first successfully parsed file, because the root_element check happens a layer above. One fix is to only try and parse .twb/.tds files.

**Comment by itsmarco** [comment] 2016-12-06 09:21
@t8y8  unfortunately I cannot. What I can tell you is that the .twbx contains a folder named TwbxExternalCache, which contains two subfolders: TwbxResultsCacheV3 & TwbxTimestampsCacheV3. These folders contains .key & .bin files. A .key file is attached. 
[.key.txt](https://github.com/tableau/document-api-python/files/633384/default.key.txt)

**Comment by t8y8** [comment] 2016-12-12 02:48
@itsmarco this should be fixed in the development branch and included in the next release.

Can you give it a quick try to confirm?

**Comment by itsmarco** [comment] 2016-12-12 10:25
@t8y8 Fixed worked. Thanks :)

**Comment by t8y8** [comment] 2016-12-12 18:05
Awesome! Thank you for verifying!

**Closed by t8y8** 2016-12-12 18:05 UTC
Labels: bug
