### ISSUE TITLE
AttributeError in Field.py 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by itsmarco** [tableau/document-api-python#135] opened 2017-03-24 13:41 UTC
Hello,

During the same project as the other bug, I tried to parse a 9.3 workbook. This workbook throws up some errors I couldn't really understand. The issue occurs on opening the workbook with Workbook().

I attached the .twb that gives these errors. This file is extracted from a .twb, as the data is private. I've also attached the traceback. 

I've tried my best troubleshooting this problem, but I couldnt really get anywhere. I think the metadata record for Calculation_5640917144906637 is responsible somehow as this seems to be the field the error occurs on, but I dont understand why. 

Good luck with this one!

On a brighter note: Of the 414 workbooks on our server, only 2 gave errors which is a pretty decent score :)

Cheers,
Marco

twb (changed filetype to .txt for github):
[demo_onderwijsopbrengsten.txt](https://github.com/tableau/document-api-python/files/868017/demo_onderwijsopbrengsten.txt)
traceback:
[traceback.txt](https://github.com/tableau/document-api-python/files/868020/traceback.txt)

**Comment by ElPincheTopo** [comment] 2020-11-18 07:19
Seems to be a duplicate of #145

**Comment by jacalata** [comment] 2021-05-29 07:45
This one was first, but the other issue  #145  has the fix in it. 
I did load this twb with the sdk from the development branch and it worked fine, but the code doesn't look fixed so we might just be handling the error better now.

**Closed by jacalata** 2021-05-29 07:45 UTC
